# Generated by Django 3.0.7 on 2020-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_token',
            field=models.CharField(default='ABC', max_length=16),
            preserve_default=False,
        ),
    ]
